# Generated by Django 2.2.10 on 2020-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=12)),
                ('reviewer_name', models.TextField(default='None')),
                ('prod_helpfulness', models.CharField(max_length=3)),
                ('prod_score', models.FloatField()),
                ('time', models.TextField()),
                ('summary', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
