# Generated by Django 2.2.10 on 2020-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='prod_helpfulness',
            field=models.FloatField(),
        ),
    ]
